language: r
cache: packages
sudo: required

apt_packages:
  #- libgsl2

r_binary_packages:
  - mvtnorm
  - bayesm
  - coda
  - Rcpp

r_packages:
  - BTYD
  - data.table
  - lintr

after_success:
  - Rscript -e 'covr::codecov()'

#warnings_are_errors: true
